### ISSUE TITLE
[enhancement] enhancements to the client

### ISSUE THREAD

**Issue by Maks7594** [Strangerrrs/Raven-bS#12]
new modules:
BowAimbot - self explanatory
BedPlates - shows bed defense on bw

removed stuff:
enemies - literally why is this here

module changes:
KillAura - instead of attacks per second make it have sliders for mincps and maxcps like autoclicker. also change the "aim smoothing" into "aim speed" 0-25
ClickGUI - add a seperate clickgui scale (using medium scaling is annoying, especially because my vision sucks), and a max modules setting that limits the modules displayed in a category at once, with this add clickgui scrolling so

new hud stuff:
Notifications - whenever you turn on a module it appears for like 1.5s and shows the module you enabled. this is useful to check if you have a module/modules on or off

other:
friends category in clickgui - allows you to manage friends easier than ever before

ok thats it i will add more in comments if i actually have more ideas bye :*

**Comment by Darkmonkey55** [comment]
> new modules: BowAimbot - self explanatory BedPlates - shows bed defense on bw
> 
> removed stuff: enemies - literally why is this here
> 
> module changes: KillAura - instead of attacks per second make it have sliders for mincps and maxcps like autoclicker. also change the "aim smoothing" into "aim speed" 0-25 ClickGUI - add a seperate clickgui scale (using medium scaling is annoying, especially because my vision sucks), and a max modules setting that limits the modules displayed in a category at once, with this add clickgui scrolling so
> 
> new hud stuff: Notifications - whenever you turn on a module it appears for like 1.5s and shows the module you enabled. this is useful to check if you have a module/modules on or off
> 
> other: friends category in clickgui - allows you to manage friends easier than ever before
> 
> ok thats it i will add more in comments if i actually have more ideas bye :*

Don't get rid of enemies, dumbest thing ive ever heard, enemies are helpful in lots of gamemodes such as the pit, if you want to target a specific person, or if you want to be able to see someone with nametags on (because it makes their name red).

 I think killaura cps is good idea but aimspeed change just seems kinda irrelevent imo. 

Im pretty sure notifications r already a thing? 

new friend gui is cool but there should also be enemies gui in it. Also add option to keep friends/enemies on close

**Comment by HMMMTH** [comment]
The ClickGUI is sometimes not fully functional on a higher Minecraft GUI scale because you cannot access all the module settings properly. This can be fixed by allowing the user to shift the view or scroll through each module list.
