### ISSUE TITLE
freecam might crash game

### ISSUE THREAD

**Issue by fedoragoated** [Strangerrrs/Raven-bS#22]
1. turn off disable on damage
2. take damage
3. turn off free cam

**Comment by Strangerrrs** [comment]
Cannot replicate, does not crash. What do you mean "might crash"

**Comment by fedoragoated** [comment]
I mean it happened once and not again. It happened when I was on test.karhu.ac server. 

A random guess: it's possible the freecam sent some really bad broken packets and the anti cheat purposefully crashed my game.

**Comment by Strangerrrs** [comment]
Provide crash log

**Comment by fedoragoated** [comment]
There does not seem to be any crash report or anything in the logs from that time. Since I cannot do anything to identify the issue or recreate it i'm just going to close this issue for now and reopen it in the future if I run into this issue again hopefully with a crash log or more information.
